name: Format
on: push
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          FORMAT_FUNC: ${{ format('{0}, {1}', 'riki', 'fuku') }}
          JOIN_FUNC: ${{ join(github.event.commits.*.message, ', ') }}