name: override-env
on: push
env:
  EXAMPLE: workflow level
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${EXAMPLE}"
      - env:
          EXAMPLE: job level
      - run: echo "${EXAMPLE}"